  version: '3.7'

  services:
    web:
      build:
        context: .
        dockerfile: Dockerfile.client
      volumes:
        - .:/code
      ports:
        - "3000:3000"
      depends_on:
        - proxy
      restart: always
    proxy:
      build:
        context: .
        dockerfile: Dockerfile.proxy
      image: proxy-server
      environment:
        YELP_API_KEY: ${YELP_API_KEY}
      restart: always
