FROM python:3.8-slim-buster

WORKDIR /app

COPY back-end/app.py back-end/requirements.txt back-end/

RUN pip3 install -r requirements.txt

ENV FLASK_APP=app.py

EXPOSE 5000

CMD ["gunicorn", "-b", ":5000", "app:app"]
